name: Build CoopBot
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout
      - uses: actions/checkout@v4
      # 2. configure java
      - name: Java config
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # 3. gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      # 4. run build
      - name: Build with Gradle
        run: ./gradlew build