name: Build CoopBot
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # 1. checkout
      - uses: actions/checkout@v4
      # 2. configure java
      - name: Java config
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # 3. gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
         gradle-version: '8.9'
      # 4. run build
      - name: Build with Gradle
        run: ./gradlew build
